### ISSUE TITLE
Bower package should not use *.min version

### ISSUE THREAD

**Issue by rastographics** [HubSpot/offline#117]
According to the bower spec (https://github.com/bower/bower.json-spec#main), the non-minified files should only be used in Main.

Using the .min version in through bower can cause problems in some build processes (ie, grunt)

Just wanted to help and point that out. Thanks!

**Comment by anthonator** [comment]
:+1:

**Comment by indolering** [comment]
It should include both.  I got an error when I tried to add a second Uglify task to the [gruntfile](https://github.com/HubSpot/offline/blob/master/Gruntfile.coffee) but it should be trivial for someone who is familiar with Grunt.

**Comment by rawls238** [comment]
https://github.com/HubSpot/offline/pull/148 should have fixed this issue
