### ISSUE TITLE
Chrome App Integration

### ISSUE THREAD

**Issue by nisaac2fly** [HubSpot/offline#118]
I am looking to at the offline package to my chrome application, however, I get the following errors.

- `window.localStorage is not available in packaged apps. Use chrome.storage.local instead.`
- `Uncaught TypeError: Cannot read property 'OFFLINE_SIMULATE' of undefined`

Here are the scripts i have added to my `index.html` file.

```html
<link rel="stylesheet" href="bower_components/offline/themes/offline-theme-default.css">
<link rel="stylesheet" href="bower_components/offline/themes/offline-language-english.css">

<link rel="stylesheet" href="bower_components/offline/themes/offline-theme-chrome-indicator.css">
<link rel="stylesheet" href="bower_components/offline/themes/offline-language-english-indicator.css">

<script src="bower_components/offline/offline.min.js"></script>
```

I also don't see offline indecator on anywhere on the page.

![image](https://cloud.githubusercontent.com/assets/1559451/5591288/57a8dbc8-9107-11e4-933e-31980edefa30.png)

Is there something simple I am missing here? 

Thanks in advance.

Nathan

**Comment by dough10** [comment]
also attempted to use this library in a chrome packaged app and had same results.

**Comment by nonameolsson** [comment]
+1 
I also get this error when loading a website in a WebView in an Android app
