### ISSUE TITLE
Offline.check() returning conflicting XMLHttpRequest

### ISSUE THREAD

**Issue by heartdev** [HubSpot/offline#121]
Note the "status" in the in-line object (0), and the "status" in the expanded object (200).  Does anyone have any ideas?  Thx in advance.

![image](https://cloud.githubusercontent.com/assets/4590504/5788345/a8f3b9a0-9de4-11e4-8f9e-e27198d3b313.png)

**Comment by zackbloom** [comment]
I believe this is common if the object changed from the time you logged it
to when you opened it in the expanded view.  Are you logging the initial
message before the request comes back?

**Comment by heartdev** [comment]
Here is my code:

`var status = Offline.check();`
`console.log("Status of Offline.check()", status);`

I'm trying to determine whether the system is online or offline before I execute another function call.  What is the best way to do this? 

I've tried using Offline.state as well (and in combination with Offline.check()), but I haven't had any luck.  I can cut (or enable) the connection and the system still thinks it's online (or offline).

**Comment by iskandar** [comment]
`Offline.check()` is not synchronous, so you'll probably want to wrap it into a promise. 

Here's a simple example. Note that `$q` is the angular promise library.

```javascript
function check() {
  var request = Offline.check();

  var deferred = $q.defer();
  request.onreadystatechange = function(e) {
    if (request.readyState !== 4) {
      return;
    }
    if ([200,304].indexOf(request.status) === -1) {
      deferred.reject(new Error('Server responded with a status of ' + request.status));
    } else {
      deferred.resolve(request);
    }
  };
  return deferred.promise;
}

````

You could then use the `check()` method like this:

```javascript
check().then(function(request) {
  console.debug("Connected, XHR is", request);
}, function(error) {
  console.debug("NOT Connected, error is", error);
});
````

Promise-wrapper from https://gist.github.com/matthewp/3099268
