### ISSUE TITLE
package.json : add a main attribute

### ISSUE THREAD

**Issue by cutesquirrel** [HubSpot/offline#122]
Hi guy,
many thanks for this great library !

Just a tiny issue : when using this library with **npm**, it uses the `package.json`.
And it misses a `main` attribute like in the `bower.json`, to indicate the library name (shouldn't be minified by default, it's hope to the developer to minify or not the JS or not #117 )

thanks a lot !
Kind regards,

**Comment by adamschwartz** [comment]
Hey @cutesquirrel, thanks for letting us know. We’ll take a look.

**Comment by cutesquirrel** [comment]
Hi,
I saw that the main attribute exists in the master branch, could you create a git tag in order to be able to use it in a package.json please ?

Many thanks
