### ISSUE TITLE
Offline with Backbone

### ISSUE THREAD

**Issue by jcrawford** [HubSpot/offline#129]
I have offline setup with my backbone application with the following options

    Offline.options.checkOnLoad = true;
    Offline.options.interceptRequests = true;
    Offline.options.requests = true;
    Offline.options.checks = {xhr: {url: CheckinApp.base_path + '/api/online'}};

This is working where if I kill my wifi connection I see the calls to /api/online failing.  When I turn the wifi off in my backbone app it still works locally, when I click an event handler that issues an ajax request then I see that in my console as a failed request.

    PUT http://jcrawford.heytix.com/guestlist/checkin/api/events/11873/guestlist/a5a4c37277 net::ERR_INTERNET_DISCONNECTED

However when my internet comes back up it does not seem to send the ajax requests to the server to sync the state.

The issue I have is this.  One tab in my interface lists guests another lists tickets.  If I am in the guests tab and I go offline and I "check in" a guest the UI updates and all works.  If I switch to the tickets tab and then back to the guests tab my entire collection is gone.  This has something to do with the localStorage because if I delete that then the collection reappears but no changes that were made while offline are present.

Screen When Wifi is OFF and BEFORE any actions
![screen shot 2015-03-25 at 11 10 24 am](https://cloud.githubusercontent.com/assets/875341/6827738/ba9825a8-d2df-11e4-901f-5c5f31e4335b.png)

After checking in a few guests
![screen shot 2015-03-25 at 11 10 37 am](https://cloud.githubusercontent.com/assets/875341/6827737/ba976a64-d2df-11e4-8c5c-2a0bac72c78e.png)

Switching from Guest tab to Tickets Tab and back to Guests Tab
![screen shot 2015-03-25 at 11 10 50 am](https://cloud.githubusercontent.com/assets/875341/6827736/ba94e898-d2df-11e4-8c37-f64962073e2b.png)

Chrome Developer Console
![screen shot 2015-03-25 at 11 10 56 am](https://cloud.githubusercontent.com/assets/875341/6827735/ba93b914-d2df-11e4-8c1a-092f8edd5ea1.png)

**Comment by indolering** [comment]
Are you using any Ajax abstractions (like jQuery) or are you making raw Ajax calls.  If you system has complex semantics, you should probably manually collect user input and create your own recovery function.

Also, are you really sure you want to allow guests to check-in offline?  What if they don't reconnect by the time they need to literally check in?
