### ISSUE TITLE
interceptRequests is ignored

### ISSUE THREAD

**Issue by DannyMoerkerke** [HubSpot/offline#131]
If I understand the docs correctly, when I set "interceptRequests" to false, it should not check on every ajax request. However I see that a huge amount of checks is fired when my application fires a large amount of ajax requests.

It seems to me that this option is ignored.

**Comment by zackbloom** [comment]
`interceptRequests` specifically disables trying to remake requests when the connection is reestablished.  You also must switch to a different check style (other than `xhr`) to disable all XHR checking.  For example:

```javascript
Offline.options.checks.active = 'image'
```
