### ISSUE TITLE
Socket trigger

### ISSUE THREAD

**Issue by philipmclifton** [HubSpot/offline#134]
Is there a method for setting connection as offline?

This would allow me to use offline to notify on a socket connection.

**Comment by Sinistralis** [comment]
You can manipulate some of the CSS with javascript to create your own goOffline() method, but I don't think there is a way built in. I had to make a workaround.

https://gist.github.com/Sinistralis/fe37c183ce492b238d55

It's a bit of a hack but it works. The moment this library supports it though I will happily remove this.

**Comment by zackbloom** [comment]
I really don't think this is in-scope.  If you really want to you can certainly try triggering the `'down'` event:

```javascript
Offline.trigger('down')
```

That's really what the UI is listening to: https://github.com/HubSpot/offline/blob/master/coffee/ui.coffee#L79
