### ISSUE TITLE
Use navigator.onLine for modern browser

### ISSUE THREAD

**Issue by bennyn** [HubSpot/offline#135]
Hello, 

I really like the "Offline" library but it would be great if it would make use of the `navigator.onLine` property for modern browser, because there is no need for them to do XML HTTP Requests all the time. 

The `navigator.onLine` property works good in all modern browsers except Firefox, so it's definetly worth to be checked ([compatibility](http://caniuse.com/#feat=online-status)). There are also callbacks for `window.ononline` and `window.onoffline`. :smiley:

**Comment by Southpaw17** [comment]
These properties work well when determining if the client has an active internet connection, but are not so good for determining if the user can actually talk to your server.  For example, if the user has an active network connection but our servers are offline for some reason, we would want the client-side application to behave as if it's offline.  This can only really be accomplished by poking the server to see if you can successfully communicate with it.

**Comment by bennyn** [comment]
Yeah, you are totally right. Sorry. I misused "Offline" to check if the client is offline. :grinning:

**Comment by indolering** [comment]
While this only checks one aspect of the connection, adding it to the control flow would improve the UX.  For example, if your strategy consists of simply disabling editing listening for this event would preemptively prevent edit attempts.  It would also improve the accuracy of the status indicator, alerting the user to a local connection issue and reducing the number of pointless "connecting" attempts.

**Comment by indolering** [comment]
Your event handler should probably include a time delay, rechecking `navigator.online` a few seconds later to allow for a portable to recover from temporary connection issues (like cycling sleep states or switching connections).

**Comment by indolering** [comment]
It appears as if the code already uses this, but the implementation is problematic as it trusts the "offline" signal entirely.

**Comment by indolering** [comment]
At any rate, please close this ticket.
