### ISSUE TITLE
Request not stored

### ISSUE THREAD

**Issue by hotkicker** [HubSpot/offline#137]
Im using the lastest 0.7.11. My problem is just as the title states. Ajax request are totally not storing and are not remade when the internet is back on. Everythign else(UI, custom check url) is working fine.

My Options:

    Offline.options = {
        checkOnLoad: true,
        interceptRequests: true,
        requests: true,
	checks: {image: {url: 'http://exmpale.com/client/pixel.jpg'}, active: 'image'}
    };

My Ajax request:

$.ajax({
						url: serverAddress+'/api/eventHandler.php',
						data: tasks[i],
						async: false,
						type: 'POST',
						timeout: 3000,
						crossDomain: true,
						success: function(responseText) { console.log(responseText); tasks.splice(i, 1); },
						error: function(responseText) { console.log("NOPE"); tasks.splice(i, 1); }
					});	

Please advise.

Thanks.

**Comment by zackbloom** [comment]
In general, making requests with `async: false` is not really ever appropriate.  I can't speak to what will or won't work in Offline if you do this.
