### ISSUE TITLE
Clarify Ajax Capabilities

### ISSUE THREAD

**Issue by indolering** [HubSpot/offline#140]
There are a few tickets related to Ajax resend feature not working for special situations (head requests in IE) or abstractions (such as jQuery's $.ajax).

I would like to see a section of the readme dedicated to documenting the behavior of vanilla Ajax calls and a feature matrix outlining support for popular abstraction libraries (such as jQuery, Angular, Polymer, etc):

|                         | Vanilla XHR | jQuery 2      | Zepto | Angular |
|---------------------|------------------|----------------|----------|------------|
| remake            | √                  | √                 | ?         | ?           |
| event handlers | √                  | $.ajax only | ?         | ?           |

If someone can clue me in on what is supported, I can modify the readme and make a PR.  It might also be nice to writeup a wiki page on how to add support for an abstraction.

**Comment by zackbloom** [comment]
In general, every service which uses the underlying `XMLHttpRequest` (the only way to make AJAX requests), should be supported.  The one exception to this is if the service-in-question is brought into the page before Offline, and makes a references to `XMLHttpRequest` before we get a chance to alias it.  Any other failure should be considered a bug.

**Comment by evanjmg** [comment]
Please put your comment in the readme @zackbloom. Thank you - I spent hours debugging this.
