### ISSUE TITLE
Offline.on() -> Offline.addEventListener()?

### ISSUE THREAD

**Issue by indolering** [HubSpot/offline#141]
I'm ignorant as to the underlying implementation, but I thought that the `.on` syntax (as in document.onload) was frowned upon because you could only register a single event handler.  Is this latter method supported and (if so) shouldn't it be used instead?

**Comment by pthorson** [comment]
Not sure it was related but there was a pull request to change the remaining instances of addEventListener to on() syntax to support IE8.

**Comment by zackbloom** [comment]
The `on` function is implemented in Offline, it is unrelated to the browser's API.  `onload` is bad because you can only bind one function that way, this is obviously not the case with our implementation.
