### ISSUE TITLE
Can not disable requests

### ISSUE THREAD

**Issue by stevennnd** [HubSpot/offline#145]
Hi,

After I import Offline.js, I am setting `Offline.options = {requests: false}` and it doesn't seem to disable requests (i.e. an ajax request made while offline is still being resent when back online).

It looks like this option is referenced only once, when requests.js is first initialised.

As I am including the .min version of Offline.js (includes requests), I don't understand how it's possible to set Offline.options before requests is loaded and have this option take effect?

Is this a bug, or am I doing something wrong?

Cheers,

Steven

**Comment by icenine457** [comment]
+1, though I did find a workaround:
```
Offline.on('up', function() {
  Offline.requests.clear();
})
```
It does seem to be broken, though, as the events are properly being honored, but not the options.
