### ISSUE TITLE
How to set text language using js?

### ISSUE THREAD

**Issue by action-this-day** [HubSpot/offline#155]
How can I set the text content with javascript instead of css? I can't use the css solution due to multilanguage on my site and I'm not going to load 20 css files just to get the right language

**Comment by adamschwartz** [comment]
One option is you can use JS to conditionally load the appropriate language CSS file.

**Comment by action-this-day** [comment]
So I can't set content using js parameters? It's not an option to load/unload css files dynamically. I need to use a js version of php's gettext function, so I don't want to put any textual content in my css files

**Comment by zackbloom** [comment]
You could also write out the CSS you need using JavaScript.  For example:

```javascript
var style = document.createElement('style');
style.innerHTML = ".offline-ui.offline-ui-up .offline-ui-content:before { content: 'Conectado'; }"
document.head.appendChild(style);
```
