### ISSUE TITLE
version 0.7.13 not published to npm

### ISSUE THREAD

**Issue by lyonlai** [HubSpot/offline#162]

**Comment by rawls238** [comment]
@zackbloom can you do this? I would but I don't have permissions to publish to npm for this project

**Comment by lyonlai** [comment]
@rawls238 thanks for the quick response.

**Comment by netsgnut** [comment]
I was going to open another issue regarding not publishing the NPM and found this issue instead :(

Currently as a workaround I have specified the git tag at `package.json`, but I think it will be nice if in the long run each every minor/major versions get published on NPM too.

**Comment by lyonlai** [comment]
it's been quite some time? Anyone can help with this?

**Comment by zackbloom** [comment]
Done, sorry for the delay!
