### ISSUE TITLE
require'ing offline-js failing in 0.7.11 from npm

### ISSUE THREAD

**Issue by peacechen** [HubSpot/offline#178]
I'm pulling offline-js from npm.  Version 0.7.11 fails trying to require it.  The "main" key is missing from the package.json.  Adding something like this should resolve it:

"main": "offline.min.js"

(offline.js is missing from the root dir, and the one under js/ looks out of date)

**Comment by also** [comment]
Thanks for reporting!

This was fixed in `v0.7.13`.
