### ISSUE TITLE
Offline.js only forwards one ajax call after reconnecting

### ISSUE THREAD

**Issue by kabilans** [HubSpot/offline#198]
So I have offline.js set up and the ui reflects the state (online/offline) correctly and I can see that it fowards the latest ajax call when I'm back online. But the problem is it only does it for the latest ajax call and disregards the rest. I do not feel like this is an intended behavior and was wondering if anyone else ran into this before or if anyone had any tips for me?

**Comment by zackbloom** [comment]
In general this is the intended behavior.  Offline only forwards one request per URL.  There is an option though which will have it also consider the body of the request: https://github.com/HubSpot/offline/blob/master/coffee/requests.coffee#L42
