### ISSUE TITLE
Missing version tag for v0.7.18

### ISSUE THREAD

**Issue by PeterDaveHello** [HubSpot/offline#228]
Hello all! I just saw that @also pushed v0.7.18 commit in 3ef194de74f70965589ecc4fd9d1d8b9ca9ad0a2, but seems the latest tag only have v0.7.17, would you please also add a git tag for 0.7.18? So that we can easily update this awesome library on CDNJS - https://cdnjs.com/libraries/offline-js, Thanks!

**Comment by also** [comment]
Done! https://github.com/HubSpot/offline/tree/v0.7.18

**Comment by PeterDaveHello** [comment]
Thanks @also
