### ISSUE TITLE
offline.js doesn't work at all

### ISSUE THREAD

**Issue by gbin1** [HubSpot/offline#23]
when i include offline.min.js and theme css to my page, and shut down the server, nothing happend when ajax request was failed.  what's wrong with it?

**Comment by vinay-kotian** [comment]
Hello,

I am using offline.js in my web application. When the connection goes down or offline, the pop up does come up but I cannot see the text. I have tried my best to find what I am missing. Am I missing some js or css files which need to be included.

**Comment by zackbloom** [comment]
@vinay-kotian Please be sure you're including both a theme and a language file: https://github.com/HubSpot/offline/tree/master/themes

**Comment by mahanandajreddy** [comment]
I am using Offline.js to show a message when internet is not there, its working fine but in sometimes Firefox 44.0 version when internet is not there than it will show alert "Your device lost internet connection" and "Attempting to reconnect" and than without internet also it will come third alert message as "Your device is connected to the internet" and alert will disappear.
         
    can anyone suggest me how to fix this issue is Firefox and some times this issue will come in chrome also.

**Comment by robertop87** [comment]
Same issue here:
When my whole computer and of course the app is offline, then the Offline.status is "up".
Browser: 60.0.3112.101 (Official Build) (64-bit)
OfflineJS version: ^0.7.18

**Comment by hardikmodi1** [comment]
Does offline.js work in localhost or I need to move to web environment?

**Comment by pratikhmehta** [comment]
Hello,

I am using offline.js in my web application. When I do offline in Google Chrom Network Tab -> Offline then it works fine, but it not able to work while I turn off my wifi.

Please help me
Thanks,

**Comment by robertop87** [comment]
@pratikhmehta perhaps my guesses this time are stupid, anyway those are the next:

1. I think you are pointing to localhost, then does not matter if you turn off your wifi, the offline.js keeps "online" for localhost.
2. I think you have the n/w cable still connected.

Maybe I'm absolutely wrong, I hope that.

Regards.

**Comment by ashah7** [comment]
Is there a way to check Internet connection if on localhost? Using offline.js

**Comment by zackbloom** [comment]
Yep, just change the URL to something which is on the internet. See https://github.com/HubSpot/offline#checking.
