### ISSUE TITLE
Great project - would love it if this could be altered to optionally refresh if online as well.

### ISSUE THREAD

**Issue by JasonBee** [HubSpot/offline#242]
We were using a combo of javascript options to detect offline status and to refresh our pages, but this one proved to be far more robust in correctly detecting offline status. Could it be augmented to optionally refresh a given page while it's online?

The added logic would work as follows:

Check connection every 240 seconds
     If up
          optionally refresh page 
     If down, 
          do nothing, 
          wait 240 more seconds
End

**Comment by Mattwmaster58** [comment]
Why not do this? 
```
setInterval(function(){
    Offline.check();
    if (Offline.state === 'up'){
        if (confirm("Reload?")){
            location.reload();
        }
    }
}, 240000)

**Comment by JasonBee** [comment]
Thank you!

It works like a charm. I made a small edit to skip the user intervention. 
`setInterval(function(){
    Offline.check();
    if (Offline.state === 'up'){
       {
            location.reload();
        }
    }
}, 240000)
`
