### ISSUE TITLE
How to set Offline.options

### ISSUE THREAD

**Issue by ijafri** [HubSpot/offline#4]
I am a newbie, please let me know the code to put after the script to disable requests (false) thanks.

**Comment by suneeltcs** [comment]
**Snake demo page also not working after disabling internet connection.**
* *Please let me know if anything else we need to do*.
* *Any steps we need to follow to run snake game*.

**Comment by lostinroom** [comment]
When connection is back, snake is not removed properly.
It throws and error.
NotFoundError: Node was not found
return document.removeChild(canvas);
