### ISSUE TITLE
Safari - Mavericks

### ISSUE THREAD

**Issue by shaneholloman** [HubSpot/offline#45]
Seems your demo and my site both won't produce this in Safari - great in chrome however!
http://yoyo.io/css

**Comment by rinogo** [comment]
@zackbloom - Can you please add this to the Readme?  It currently says that offline.js supports "Modern Chrome, Firefox, Safari and IE8+".  If Safari doesn't support offline events, this is only "kind of" true; it is definitely misleading.  It would be nice to know of this limitation up front.

**Comment by zackbloom** [comment]
Done in https://github.com/HubSpot/offline/commit/b30eccbb46078f28300224fb4591b4b9eb027a62

**Comment by rinogo** [comment]
Thanks!  And thanks for your work maintaining this library! :)
