### ISSUE TITLE
Option "requests" is ignored

### ISSUE THREAD

**Issue by Fensterbank** [HubSpot/offline#73]
Hello,

I noticed that the Option "requests" is ignored completeley.
In offline.js, requests is not in the variable defaultOptions, what means in requests.js (Line 65) the code Offline.getOption('requests') returns undefined and the condition is true.

```
if (Offline.getOption('requests') !== false) {
      Offline.on('confirmed-up', function() {
        if (waitingOnConfirm) {
          waitingOnConfirm = false;
          return clear();
        }
      });
      Offline.on('up', flush);
```
This whole code is executed directly after loading the javascript file.

A user has no possibility to enable or disable the "requests"-Feature, because when the options are set in code programmatically, the events for doing the requests are already binded.

**Comment by vivex** [comment]
Now it seems to be fixed, so close this issue :)

**Comment by rawls238** [comment]
This was fixed here: https://github.com/HubSpot/offline/pull/163 so closing. Please comment if this is still an issue
