### ISSUE TITLE
Unable to integrate offline.js

### ISSUE THREAD

**Issue by raul1991** [HubSpot/offline#82]
Added the js and css file. and this js code but still no luck .However in the console i see the request for favicon happening and doing the stuff like 404 on connected.

#js code

$(function(){

        var 
            $online = $('.online'),
            $offline = $('.offline');

        Offline.on('confirmed-down', function () {
            $online.fadeOut(function () {
                $offline.fadeIn();
            });
        });

        Offline.on('confirmed-up', function () {
            $offline.fadeOut(function () {
                $online.fadeIn();
            });
        });

    });

I am using chrome browser. Version 31.0.1650.63

**Comment by rawls238** [comment]
did you manage to figure this out? can we close this issue?
