### ISSUE TITLE
Offline.js doesn't work with Firefox 29.0.1

### ISSUE THREAD

**Issue by michaljagielski-sc** [HubSpot/offline#83]
Hello,
It can be tested here: http://github.hubspot.com/offline/docs/welcome/, that after disconnecting from the internet it doesn't show anything. Works in Chrome (35.0) and IE11.

**Comment by nadeemja** [comment]
Still does not work with firefox. Using Firefox 36 and Offline 0.7.10.

**Comment by sweh** [comment]
Doesn't work for me, too. Is this project dead?

**Comment by zackbloom** [comment]
Sorry for the delay in responding to this.  Firefox does not fire the `offline` and `online` events in the way that other browsers do.  You can test this by running this Fiddle with your console open and disconnecting your internet connection: http://jsfiddle.net/L507acnc/

In Firefox, we get no events, in Chrome, we get the events we need.  This means the only way of detecting actual network status in FF is for an actual HTTP request to fail.  On the Offline homepage, there are no requests, so this never happens.  You can manually run a check though by executing `Offline.check()` in the console, and you will see it correctly update.

If offline detection is very important to you, but you never make any requests (an odd combo), you could run `Offline.check` periodically:

```javascript
setInterval(function(){
  Offline.check();
}, 5000);
```

**Comment by zackbloom** [comment]
Re the IE11 issue, please open another issue if it's reproducible.  Status 0 often means the browser couldn't make a connection for an internal reason, it's possible your network connection was not truly 'up' yet.

**Comment by sweh** [comment]
Hi,

well, those events are working, at least on the Mozilla Developer Network. Just have a look at https://developer.mozilla.org/en-US/docs/Online_and_offline_events in the latest Firefox, there is a JS Test which works great when switching between Online and Offline mode. Could you update Offline.js to support the Firefox behavior?

Thanks a lot,
  Sebastian

**Comment by zackbloom** [comment]
Sebastian, have you tried the fiddle I included in my response? If you see a technical difference between my example in that fiddle and what the MDN article instructs, please enumerate it. Does the fiddle work for you?

**Comment by sweh** [comment]
No, the Fiddle does not work for me. Does the MDN-"Fiddle" work for you?

**Comment by sweh** [comment]
And even JSFiddle recognizes going into Offline-Mode immediately and gives me a JS-Popup asking if I know what I'm doing.

**Comment by zackbloom** [comment]
It does not work for me on Firefox 36 / OSX.  If the fiddle doesn't work for you, I would love to hear what you see as the difference between what we're doing in the fiddle, and what Mozilla is doing in their example.  In any case, neither seems to work on OSX, making it difficult for me to examine.

**Comment by sweh** [comment]
Here is a working example: https://bug336359.bugzilla.mozilla.org/attachment.cgi?id=220609 I don't get it to work in JSFiddle, I assume JSFiddle is not the right place for those kind of tests. But this example is definitely working in FF36 and OS X (Yosemite).

The difference to me is, that the events are bind to document.body. Maybe they do no longer toggle to the window properly in firefox.

**Comment by zackbloom** [comment]
Thanks for working with me on this.  If you're interested, you can see it not working for me: https://vimeo.com/122614412.  It may take the video a bit to upload.

I am using OS X 10.10 and Firefox 36.0.1.  Without being able to see the mozilla page work, it's difficult for me to understand what is going on.

**Comment by sweh** [comment]
Ok, you are disabling your internet connection. This is not whats meant in this ticket. In Firefox Menu, go to "File" and select "Work offline" or "Offline mode" (I don't know the right english version, working with a german translation here). This puts the Browser in Offline mode, which is different to "going really offline" but in terms of Offline.js should do exactly the same: report that we are offline.

I have debugged Offline.js and found out the problem. The events fire fine, but in case of the offline event what Offline.js does is call Offline.confirmDown() which makes an ajax to confirm being offline. This does not work. Instead you should also check out ```navigator.onLine```, and if this is ```false```, set Offline.js state to false as well.

Could you also please make a new release? The last changes concerning 500 errors setting the state of Offline.js to false are not in the current release available via e.g. bower.

Thanks in advance.

**Comment by sweh** [comment]
Oh, you are disabling your internet connection. This is not what I meant but what is meant in this ticket, sorry for that mess. To make the Mozzilla Demo work, in Firefox menu, go to "File" and select "Work offline" or "Offline mode" (I don't know the right english version, working with a german translation here). This puts the Browser in Offline mode, which is different to "going really offline" but in terms of Offline.js should do exactly the same: report that we are offline.

**Comment by zackbloom** [comment]
Ah, I understand what you're saying.  This was never the intended functionality of Offline.  The biggest reason for this is A. It is unclear how many users actually know how to do this, as so few modern websites support it and B. Offline's method for retrying requests is probably too simplistic for an app which is intended to be used offline for an extended period.

**Comment by vivex** [comment]
Adding this code worked fine for me,

if (navigator.userAgent.indexOf("Firefox") > 0) {
console.log("Its FireFox");
setInterval(function(){
  Offline.check();
}, 5000);
}

Now its working fine with firefox also.

**Comment by mahanandajreddy** [comment]
where we to add this code, offline.js or 
var checkInternetConnection = function(){
		  var req = new XMLHttpRequest();
		 req.open('GET', "IMG_URL", true);
		  req.send();
		}
		setInterval(checkInternetConnection, 5000);
