### ISSUE TITLE
Code 503 should mean down

### ISSUE THREAD

**Issue by ghplink** [HubSpot/offline#89]
Scenario: Apache HTTP server forwards requests to a tomcat web server. In case tomcat is down, the apache sends a 503 (server temporarily not available). Offline.js should recoginize that as down, instead it says up.

**Comment by gustavomick** [comment]
sorry but i dont get it, why offlinejs cant provide both solutions (sever and client check)? 
what about adding response.status to result event like confirmed-up / confirmed-down or better create confirmed event with http status and let use it. 
nice lib thanks.
