### ISSUE TITLE
502 Bad Gateway should be a down event

### ISSUE THREAD

**Issue by leehambley** [HubSpot/offline#99]
I'm using this on a proxied nginx site, and there's every possibility that the web UI is up (http://www.my-site.com/) but that the nginx proxied API server to which it talks is not (http://www.my-site.com/api/, http://api.my-site.com/)

For that reason, I implemented a simple endpoint `www.my-site.com//api/ping` (also `api.my-site.com/ping`) which returns `502 Bad Gateway` when the API server is down, and `204 No Content` otherwise.

I think API errors, in particular should be considered to be "down" (although I see the value in Offline.js being to check if the *user's browser is offline*, but it's so, so close to being useful out of the box for this rather common use-case.

**Comment by asabhaney** [comment]
+1

**Comment by indolering** [comment]
Please close.
